import { ComparisonData } from './pageTypes';

export const comparisons: ComparisonData[] = [
  {
    slug: 'california-vs-texas',
    kind: 'state-vs-state',
    title: 'California vs. Texas: Buy or Rent?',
    subtitle: 'Two of the largest U.S. housing markets, side by side.',
    sideA: {
      name: 'California',
      highlights: [
        'Median home price above $750,000',
        'Property tax rate around 0.75%',
        'Strong long-term appreciation trend',
      ],
    },
    sideB: {
      name: 'Texas',
      highlights: [
        'Median home price near $300,000',
        'Property tax rate often 1.6-2.2%',
        'No state income tax',
      ],
    },
    bluf:
      'Renting often wins in coastal California unless you can stay 8+ years. Texas favors buying faster, but high property taxes narrow the gap.',
    body: [
      'California housing prices reflect constrained supply and high incomes in coastal metros. The result is a high price-to-rent ratio, which generally favors renting for shorter stays.',
      'Texas sees more affordable entry prices and no state income tax, but elevated property tax rates change the math. Break-even can arrive in 4-6 years in many metros.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$750,000', b: '$300,000' },
      { label: 'Median rent', a: '$2,800/mo', b: '$1,700/mo' },
      { label: 'Property tax', a: '~0.75%', b: '~1.80%' },
      { label: 'Price-to-rent ratio', a: '22.3', b: '14.7' },
      { label: 'Typical break-even', a: '8-10 yrs', b: '4-6 yrs' },
    ],
    faq: [
      {
        question: 'Is it cheaper to rent in California or Texas?',
        answer:
          'Renting is often closer to mortgage cost in Texas, while renting in California is usually substantially cheaper than the monthly cost of buying a median-priced home.',
      },
      {
        question: 'Where does buying break even faster?',
        answer:
          'Texas typically reaches a break-even point within 4-6 years in most major metros. California coastal metros often require 8-10+ years.',
      },
    ],
    meta: {
      title: 'California vs. Texas: Buy or Rent Comparison',
      description:
        'Compare buying and renting economics in California vs. Texas. Median prices, property tax, and break-even analysis.',
      keywords: ['california vs texas', 'buy vs rent', 'housing comparison'],
    },
  },
  {
    slug: 'florida-vs-new-york',
    kind: 'state-vs-state',
    title: 'Florida vs. New York: Buy or Rent?',
    subtitle: 'Tax structure and housing supply shape this decision.',
    sideA: {
      name: 'Florida',
      highlights: ['No state income tax', 'Insurance costs elevated', 'Growing population'],
    },
    sideB: {
      name: 'New York',
      highlights: ['High price-to-rent in NYC', 'Strong tenant protections', 'High state taxes'],
    },
    bluf: 'Florida generally favors buying in 3-5 years; New York favors renting longer, especially in NYC co-ops.',
    body: [
      'Florida offers lower entry prices outside premium coastal markets and no state income tax. Rising insurance premiums are an important cost to model.',
      'New York has wide variance. Upstate favors buying quickly. NYC co-ops have high maintenance fees and transfer taxes that push break-even far out.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$395,000', b: '$465,000' },
      { label: 'Median rent', a: '$1,950/mo', b: '$2,100/mo' },
      { label: 'Property tax', a: '~0.80%', b: '~1.40%' },
      { label: 'Typical break-even', a: '4-6 yrs', b: '6-10 yrs' },
    ],
    faq: [
      {
        question: 'Does Florida really have no income tax impact on this decision?',
        answer:
          'No state income tax increases disposable income available for housing, which can improve affordability for both renters and buyers.',
      },
    ],
    meta: {
      title: 'Florida vs. New York: Buy or Rent',
      description: 'Compare housing economics in Florida vs. New York with median prices and tax structure.',
    },
  },
  {
    slug: 'texas-vs-florida',
    kind: 'state-vs-state',
    title: 'Texas vs. Florida: Buy or Rent?',
    subtitle: 'No-income-tax states with different housing cost profiles.',
    sideA: { name: 'Texas', highlights: ['High property tax', 'Low entry prices', 'Strong job growth'] },
    sideB: { name: 'Florida', highlights: ['Rising insurance', 'No income tax', 'Coastal price premium'] },
    bluf: 'Texas favors buying earlier in suburbs; Florida depends heavily on insurance and HOA exposure.',
    body: [
      'Both states skip state income tax, so the housing math is driven by property taxes, insurance, and appreciation assumptions.',
      'Texas property tax can exceed 2% in some counties. Florida insurance can rival that cost in coastal zones.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$300,000', b: '$395,000' },
      { label: 'Property tax', a: '~1.80%', b: '~0.80%' },
      { label: 'Insurance risk', a: 'Moderate', b: 'High coastal' },
    ],
    faq: [
      { question: 'Which state has cheaper total housing costs?', answer: 'It depends on the metro and whether coastal insurance applies.' },
    ],
    meta: {
      title: 'Texas vs. Florida: Buy or Rent',
      description: 'How no-income-tax states Texas and Florida compare for buying and renting.',
    },
  },
  {
    slug: 'ohio-vs-michigan',
    kind: 'state-vs-state',
    title: 'Ohio vs. Michigan: Buy or Rent?',
    subtitle: 'Affordable Midwest markets with similar break-even profiles.',
    sideA: { name: 'Ohio', highlights: ['Very affordable entry prices', 'Stable rental market'] },
    sideB: { name: 'Michigan', highlights: ['Low price-to-rent ratio', 'Winter cost considerations'] },
    bluf: 'Both states favor buying within 3-4 years in most metros when you plan to stay.',
    body: [
      'Low home prices combined with moderate rents keep the price-to-rent ratio low in both states.',
      'Winter heating, insurance, and maintenance are important inputs for total cost of ownership.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$225,000', b: '$235,000' },
      { label: 'Median rent', a: '$1,050/mo', b: '$1,100/mo' },
      { label: 'Typical break-even', a: '3-4 yrs', b: '3-4 yrs' },
    ],
    faq: [{ question: 'Is buying a clear win in the Midwest?', answer: 'Often, yes — especially if you plan to stay 4+ years and have stable income.' }],
    meta: {
      title: 'Ohio vs. Michigan: Buy or Rent',
      description: 'Compare Ohio and Michigan for buying versus renting with local housing data.',
    },
  },
  {
    slug: 'washington-vs-oregon',
    kind: 'state-vs-state',
    title: 'Washington vs. Oregon: Buy or Rent?',
    subtitle: 'Pacific Northwest neighbors with different tax structures.',
    sideA: { name: 'Washington', highlights: ['No state income tax', 'Seattle premium'] },
    sideB: { name: 'Oregon', highlights: ['State income tax applies', 'No sales tax'] },
    bluf: 'Rent-first strategies work in Seattle and Portland for stays under 6 years; buy earlier in smaller metros.',
    body: [
      'Both states have strong long-term appreciation. The tax treatment differs significantly.',
      'HOA and condo rules are strict in many PNW metros, which affects the buy-side math.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$610,000', b: '$495,000' },
      { label: 'Property tax', a: '~0.90%', b: '~0.90%' },
    ],
    faq: [{ question: 'Does Oregon income tax change the math?', answer: 'It reduces disposable income for housing for both renters and buyers.' }],
    meta: {
      title: 'Washington vs. Oregon: Buy or Rent',
      description: 'Compare housing economics in Washington vs. Oregon with full cost analysis.',
    },
  },
  {
    slug: 'new-york-vs-los-angeles',
    kind: 'city-vs-city',
    title: 'New York City vs. Los Angeles: Buy or Rent?',
    subtitle: 'Two of the most expensive U.S. housing markets compared.',
    sideA: { name: 'New York City', highlights: ['Co-op and condo dominant', 'Transfer taxes steep'] },
    sideB: { name: 'Los Angeles', highlights: ['Prop 13 property tax cap', 'Single-family heavy'] },
    bluf: 'Both cities heavily favor renting for stays under 7-10 years; LA tends to break even slightly sooner than NYC.',
    body: [
      'NYC closing costs can exceed 5% due to mortgage recording tax and mansion tax. LA has simpler closing structures but high entry prices.',
      'Prop 13 in California provides long-term property tax protection that slowly favors long-tenure owners.',
    ],
    metricsTable: [
      { label: 'Median home price', a: '$750,000', b: '$885,000' },
      { label: 'Median rent', a: '$3,200/mo', b: '$2,800/mo' },
      { label: 'Break-even', a: '8-10 yrs', b: '7-9 yrs' },
    ],
    faq: [{ question: 'Why is buying so expensive in NYC?', answer: 'High purchase prices, co-op fees, transfer taxes, and steep closing costs all push the break-even point out.' }],
    meta: { title: 'NYC vs. LA: Buy or Rent', description: 'Buy vs. rent in New York City compared to Los Angeles.' },
  },
  {
    slug: 'austin-vs-dallas',
    kind: 'city-vs-city',
    title: 'Austin vs. Dallas: Buy or Rent?',
    subtitle: 'Texas metros with different appreciation and tax profiles.',
    sideA: { name: 'Austin', highlights: ['Higher prices', 'Strong appreciation', 'Tech hub'] },
    sideB: { name: 'Dallas', highlights: ['Lower prices', 'Diversified economy', 'High property tax'] },
    bluf: 'Dallas breaks even sooner; Austin wins more on long-term appreciation if you stay 7+ years.',
    body: ['Austin had the strongest recent appreciation in Texas but also the biggest cooldown.', 'Dallas has deeper rental supply, which moderates rent growth.'],
    metricsTable: [
      { label: 'Median home price', a: '$540,000', b: '$410,000' },
      { label: 'Median rent', a: '$2,100/mo', b: '$1,700/mo' },
    ],
    faq: [{ question: 'Which metro is cheaper overall?', answer: 'Dallas has a lower entry price but similar property tax exposure.' }],
    meta: { title: 'Austin vs. Dallas: Buy or Rent', description: 'Austin vs. Dallas housing comparison for buyers and renters.' },
  },
  {
    slug: 'miami-vs-atlanta',
    kind: 'city-vs-city',
    title: 'Miami vs. Atlanta: Buy or Rent?',
    subtitle: 'Two Southeast hubs with different cost structures.',
    sideA: { name: 'Miami', highlights: ['High insurance cost', 'Condo heavy', 'No state income tax'] },
    sideB: { name: 'Atlanta', highlights: ['Affordable single-family', 'Moderate property tax'] },
    bluf: 'Atlanta favors buying sooner; Miami insurance and HOA make renting more competitive for shorter stays.',
    body: ['Miami coastal insurance has risen sharply, which changes break-even analysis.', 'Atlanta offers more single-family entry options at moderate price points.'],
    metricsTable: [
      { label: 'Median home price', a: '$585,000', b: '$400,000' },
      { label: 'Insurance risk', a: 'High', b: 'Low' },
    ],
    faq: [{ question: 'How much can Miami insurance add to cost?', answer: 'Hundreds to thousands of dollars per year depending on zone and property type.' }],
    meta: { title: 'Miami vs. Atlanta: Buy or Rent', description: 'Miami vs. Atlanta housing comparison.' },
  },
  {
    slug: 'chicago-vs-houston',
    kind: 'city-vs-city',
    title: 'Chicago vs. Houston: Buy or Rent?',
    subtitle: 'Two large metros with very different property tax profiles.',
    sideA: { name: 'Chicago', highlights: ['High property tax', 'Stable prices'] },
    sideB: { name: 'Houston', highlights: ['No zoning', 'High property tax', 'Low entry price'] },
    bluf: 'Houston typically wins for buyers at lower entry points; Chicago property tax can erode ownership savings.',
    body: ['Cook County property tax can push effective rates above 2%.', 'Houston affordability is strong but insurance and flood risk must be modeled.'],
    metricsTable: [
      { label: 'Median home price', a: '$330,000', b: '$285,000' },
      { label: 'Property tax', a: '~2.10%', b: '~1.85%' },
    ],
    faq: [{ question: 'Which is more affordable long term?', answer: 'Houston often wins if insurance and flood costs are manageable.' }],
    meta: { title: 'Chicago vs. Houston: Buy or Rent', description: 'Chicago vs. Houston housing comparison.' },
  },
  {
    slug: 'denver-vs-phoenix',
    kind: 'city-vs-city',
    title: 'Denver vs. Phoenix: Buy or Rent?',
    subtitle: 'Mountain West and Southwest hubs compared.',
    sideA: { name: 'Denver', highlights: ['Strong appreciation history', 'Moderate property tax'] },
    sideB: { name: 'Phoenix', highlights: ['Rapid rent growth', 'Heat cost consideration'] },
    bluf: 'Both markets favor buyers at 5-7 years; Phoenix has seen sharper recent price swings.',
    body: ['Denver has historically been a steady-appreciation market.', 'Phoenix had large price movements during the last cycle.'],
    metricsTable: [
      { label: 'Median home price', a: '$575,000', b: '$440,000' },
    ],
    faq: [{ question: 'Is Phoenix overbuilt?', answer: 'Supply has expanded significantly, moderating rent growth recently.' }],
    meta: { title: 'Denver vs. Phoenix: Buy or Rent', description: 'Denver vs. Phoenix housing comparison.' },
  },
  {
    slug: 'san-diego-vs-san-antonio',
    kind: 'city-vs-city',
    title: 'San Diego vs. San Antonio: Buy or Rent?',
    subtitle: 'Coastal California versus affordable Texas metro.',
    sideA: { name: 'San Diego', highlights: ['Premium coastal prices', 'Prop 13 benefit'] },
    sideB: { name: 'San Antonio', highlights: ['Very affordable', 'High property tax'] },
    bluf: 'San Antonio favors buying quickly; San Diego favors long-tenure owners or renters.',
    body: ['San Diego has among the highest entry prices in the U.S.', 'San Antonio is among the most affordable large Texas metros.'],
    metricsTable: [{ label: 'Median home price', a: '$920,000', b: '$275,000' }],
    faq: [{ question: 'Does San Antonio property tax offset the low price?', answer: 'Partially, but overall monthly ownership cost is still much lower.' }],
    meta: { title: 'San Diego vs. San Antonio: Buy or Rent', description: 'San Diego vs. San Antonio housing comparison.' },
  },
  {
    slug: 'philadelphia-vs-charlotte',
    kind: 'city-vs-city',
    title: 'Philadelphia vs. Charlotte: Buy or Rent?',
    subtitle: 'East Coast city compared to a fast-growing Southeast hub.',
    sideA: { name: 'Philadelphia', highlights: ['Diverse housing stock', 'Moderate prices'] },
    sideB: { name: 'Charlotte', highlights: ['Strong population growth', 'New construction'] },
    bluf: 'Both favor buying at 4-6 years with stable income and plans to stay.',
    body: ['Philadelphia has older housing stock, which impacts maintenance budgeting.', 'Charlotte offers abundant new construction and modern amenities.'],
    metricsTable: [{ label: 'Median home price', a: '$295,000', b: '$395,000' }],
    faq: [{ question: 'Which market is more stable?', answer: 'Philadelphia has historically been more stable; Charlotte has higher growth variance.' }],
    meta: { title: 'Philadelphia vs. Charlotte: Buy or Rent', description: 'Philadelphia vs. Charlotte housing comparison.' },
  },
  {
    slug: 'jacksonville-vs-tampa',
    kind: 'city-vs-city',
    title: 'Jacksonville vs. Tampa: Buy or Rent?',
    subtitle: 'Two Florida metros with different coastal exposure.',
    sideA: { name: 'Jacksonville', highlights: ['Lower entry price', 'Moderate insurance'] },
    sideB: { name: 'Tampa', highlights: ['Higher price growth', 'Coastal insurance premium'] },
    bluf: 'Jacksonville breaks even faster on pure cost; Tampa offers stronger appreciation upside.',
    body: ['Florida insurance has increased sharply in recent years, especially near the Gulf.', 'Jacksonville tends to have lower flood and hurricane exposure than Tampa Bay.'],
    metricsTable: [{ label: 'Median home price', a: '$310,000', b: '$385,000' }],
    faq: [{ question: 'Does flood zone affect the buy decision?', answer: 'Yes — flood insurance can materially change total monthly cost of ownership.' }],
    meta: { title: 'Jacksonville vs. Tampa: Buy or Rent', description: 'Jacksonville vs. Tampa Florida comparison.' },
  },
  {
    slug: 'boston-vs-seattle',
    kind: 'city-vs-city',
    title: 'Boston vs. Seattle: Buy or Rent?',
    subtitle: 'High-income, high-price coastal metros.',
    sideA: { name: 'Boston', highlights: ['Older housing stock', 'High property tax variance'] },
    sideB: { name: 'Seattle', highlights: ['No state income tax', 'Tech-driven demand'] },
    bluf: 'Both cities favor renting under 6 years; Seattle tends to break even slightly faster for buyers.',
    body: ['Boston condos and triple-deckers dominate many neighborhoods, with varying HOA/maintenance profiles.', 'Seattle has stricter condo rules and slower inventory turnover.'],
    metricsTable: [{ label: 'Median home price', a: '$720,000', b: '$820,000' }],
    faq: [{ question: 'Which city has faster appreciation?', answer: 'Seattle has historically shown stronger recent appreciation driven by tech hiring.' }],
    meta: { title: 'Boston vs. Seattle: Buy or Rent', description: 'Boston vs. Seattle housing comparison.' },
  },
  {
    slug: 'nashville-vs-raleigh',
    kind: 'city-vs-city',
    title: 'Nashville vs. Raleigh: Buy or Rent?',
    subtitle: 'Two of the fastest-growing Southeast metros.',
    sideA: { name: 'Nashville', highlights: ['Tourism-driven demand', 'No state income tax'] },
    sideB: { name: 'Raleigh', highlights: ['Research Triangle jobs', 'Moderate property tax'] },
    bluf: 'Raleigh generally reaches buy break-even a bit faster; Nashville offers stronger short-term rental exposure.',
    body: ['Nashville short-term rental rules have shifted, changing investor math.', 'Raleigh Triangle jobs anchor stable primary-residence demand.'],
    metricsTable: [{ label: 'Median home price', a: '$455,000', b: '$410,000' }],
    faq: [{ question: 'Are these markets overheated?', answer: 'Both saw sharp growth but have moderated recently with higher rates.' }],
    meta: { title: 'Nashville vs. Raleigh: Buy or Rent', description: 'Nashville vs. Raleigh housing comparison.' },
  },
  {
    slug: 'urban-nyc-vs-suburban-long-island',
    kind: 'urban-vs-suburban',
    title: 'Urban NYC vs. Suburban Long Island: Buy or Rent?',
    subtitle: 'Same metro, very different ownership math.',
    sideA: { name: 'NYC (urban)', highlights: ['Rent-friendly', 'High transaction costs', 'No car needed'] },
    sideB: { name: 'Long Island (suburban)', highlights: ['Single-family dominant', 'High property tax', 'Commuting cost'] },
    bluf: 'NYC favors renting for many; Long Island favors buying for long-tenure families despite high property taxes.',
    body: ['Nassau and Suffolk property taxes are among the highest in the country but reflect school funding.', 'NYC transaction costs make short-term buying costly.'],
    metricsTable: [{ label: 'Property tax', a: '~0.88%', b: '~2.2%' }],
    faq: [{ question: 'Does commuting cost flip the math?', answer: 'It can — model LIRR or driving costs as part of the housing decision.' }],
    meta: { title: 'Urban NYC vs. Suburban Long Island: Buy or Rent', description: 'Urban vs. suburban analysis for NYC metro.' },
  },
  {
    slug: 'urban-san-francisco-vs-suburban-bay-area',
    kind: 'urban-vs-suburban',
    title: 'Urban San Francisco vs. Suburban Bay Area: Buy or Rent?',
    subtitle: 'City apartments versus suburban single-family homes.',
    sideA: { name: 'San Francisco (urban)', highlights: ['Condo dominant', 'Rent control exposure'] },
    sideB: { name: 'Suburbs (Peninsula/East Bay)', highlights: ['Higher entry prices', 'Better schools in many areas'] },
    bluf: 'Rent if you might move within 6 years; buy suburban if you will stay 8+ years with family needs.',
    body: ['SF rent control benefits long-tenure renters.', 'Peninsula and Silicon Valley suburbs carry premium entry prices with Prop 13 protection.'],
    metricsTable: [{ label: 'Median condo (SF)', a: '$1.1M', b: 'Suburban SFH $1.6M' }],
    faq: [{ question: 'Does Prop 13 favor suburban buyers?', answer: 'It provides long-term property tax protection, which is more valuable with long tenure.' }],
    meta: { title: 'Urban SF vs. Suburban Bay Area: Buy or Rent', description: 'San Francisco urban vs. suburban comparison.' },
  },
  {
    slug: 'urban-chicago-vs-suburban-naperville',
    kind: 'urban-vs-suburban',
    title: 'Urban Chicago vs. Suburban Naperville: Buy or Rent?',
    subtitle: 'Downtown condo vs. suburban single-family home.',
    sideA: { name: 'Chicago (urban)', highlights: ['Condo and rental rich', 'High city property tax'] },
    sideB: { name: 'Naperville (suburban)', highlights: ['Family-oriented', 'Strong schools', 'High property tax'] },
    bluf: 'Suburban buying favors stable families with long tenure; urban renting fits flexible careers.',
    body: ['Cook County and DuPage County property taxes are both high but fund different services.', 'Commute time and cost should be part of the model.'],
    metricsTable: [{ label: 'Median home price', a: '$330,000', b: '$540,000' }],
    faq: [{ question: 'Why are property taxes so high?', answer: 'They fund schools, pensions, and services; the effective rate can exceed 2%.' }],
    meta: { title: 'Urban Chicago vs. Suburban Naperville: Buy or Rent', description: 'Chicago urban vs. suburban comparison.' },
  },
  {
    slug: 'urban-boston-vs-suburban-cambridge-somerville',
    kind: 'urban-vs-suburban',
    title: 'Urban Boston vs. Inner Suburbs: Buy or Rent?',
    subtitle: 'Close-in Cambridge and Somerville versus downtown Boston.',
    sideA: { name: 'Downtown Boston', highlights: ['Highest entry prices', 'Condo dominant'] },
    sideB: { name: 'Cambridge/Somerville', highlights: ['Strong appreciation', 'Mixed triple-deckers'] },
    bluf: 'Inner suburbs often match Boston downtown appreciation with slightly lower entry points.',
    body: ['Triple-decker condos offer smaller entry prices with shared-maintenance tradeoffs.', 'Downtown Boston carries premium pricing reflecting Seaport and Back Bay demand.'],
    metricsTable: [{ label: 'Median condo', a: '$900,000', b: '$750,000' }],
    faq: [{ question: 'Are inner suburbs cheaper over time?', answer: 'Entry price is lower; long-term appreciation is similar.' }],
    meta: { title: 'Urban Boston vs. Inner Suburbs: Buy or Rent', description: 'Boston urban vs. suburban comparison.' },
  },
  {
    slug: 'new-jersey-vs-connecticut',
    kind: 'state-vs-state',
    title: 'New Jersey vs. Connecticut: Buy or Rent?',
    subtitle: 'Two high-tax Northeast states with strong schools.',
    sideA: { name: 'New Jersey', highlights: ['Highest property tax in U.S.', 'Commuter corridors'] },
    sideB: { name: 'Connecticut', highlights: ['High property tax', 'Fairfield County premium'] },
    bluf: 'Both states require long tenure (6-8+ years) for buying to beat renting in most suburbs.',
    body: ['NJ property tax often exceeds 2.2%; CT averages slightly lower but Fairfield County is expensive.', 'Both rely on strong public schools as key ownership drivers.'],
    metricsTable: [{ label: 'Property tax', a: '~2.20%', b: '~1.80%' }],
    faq: [{ question: 'Why are these states so tax-heavy?', answer: 'High-quality public services and schools are funded largely through property taxes.' }],
    meta: { title: 'New Jersey vs. Connecticut: Buy or Rent', description: 'NJ vs. CT housing comparison.' },
  },
  {
    slug: 'arizona-vs-nevada',
    kind: 'state-vs-state',
    title: 'Arizona vs. Nevada: Buy or Rent?',
    subtitle: 'Sunbelt states with different tax structures.',
    sideA: { name: 'Arizona', highlights: ['State income tax', 'Retirement-friendly'] },
    sideB: { name: 'Nevada', highlights: ['No state income tax', 'Las Vegas tourism'] },
    bluf: 'Both break even at 4-5 years for typical buyers; Nevada edges out on tax treatment.',
    body: ['Both have seen volatile housing cycles historically.', 'Water cost and HOA structures are important to model.'],
    metricsTable: [{ label: 'Median home price', a: '$425,000', b: '$435,000' }],
    faq: [{ question: 'Are HOAs common here?', answer: 'Yes — many newer subdivisions in both states include mandatory HOAs.' }],
    meta: { title: 'Arizona vs. Nevada: Buy or Rent', description: 'Arizona vs. Nevada housing comparison.' },
  },
  {
    slug: 'north-carolina-vs-south-carolina',
    kind: 'state-vs-state',
    title: 'North Carolina vs. South Carolina: Buy or Rent?',
    subtitle: 'Carolina neighbors with different metro growth profiles.',
    sideA: { name: 'North Carolina', highlights: ['Research Triangle', 'Charlotte financial hub'] },
    sideB: { name: 'South Carolina', highlights: ['Lower entry prices', 'Coastal insurance risk'] },
    bluf: 'Both favor buying within 4 years for stable households; coastal SC requires insurance modeling.',
    body: ['NC metros have faster job growth; SC has more retirement-driven demand.', 'Myrtle Beach and Charleston coastal insurance has risen.'],
    metricsTable: [{ label: 'Median home price', a: '$355,000', b: '$295,000' }],
    faq: [{ question: 'Which state has better schools?', answer: 'Highly variable by county in both.' }],
    meta: { title: 'North Carolina vs. South Carolina: Buy or Rent', description: 'NC vs. SC housing comparison.' },
  },
  {
    slug: 'georgia-vs-alabama',
    kind: 'state-vs-state',
    title: 'Georgia vs. Alabama: Buy or Rent?',
    subtitle: 'Affordable Southeast neighbors.',
    sideA: { name: 'Georgia', highlights: ['Atlanta job hub', 'Film industry'] },
    sideB: { name: 'Alabama', highlights: ['Very low property tax', 'Low entry prices'] },
    bluf: 'Alabama has one of the fastest buy break-evens in the country; Georgia is competitive but costlier.',
    body: ['Alabama has exceptionally low property tax, which shifts total cost of ownership down.', 'Georgia metros have seen stronger appreciation recently.'],
    metricsTable: [{ label: 'Property tax', a: '~0.90%', b: '~0.41%' }],
    faq: [{ question: 'Is Alabama really that cheap to own in?', answer: 'Yes — low taxes combined with low entry prices make ownership affordable quickly.' }],
    meta: { title: 'Georgia vs. Alabama: Buy or Rent', description: 'Georgia vs. Alabama housing comparison.' },
  },
  {
    slug: 'minnesota-vs-wisconsin',
    kind: 'state-vs-state',
    title: 'Minnesota vs. Wisconsin: Buy or Rent?',
    subtitle: 'Upper Midwest states with similar climates and different metros.',
    sideA: { name: 'Minnesota', highlights: ['Twin Cities hub', 'Moderate property tax'] },
    sideB: { name: 'Wisconsin', highlights: ['Affordable statewide', 'Stable rental market'] },
    bluf: 'Both favor buying in 3-5 years for stable households; Wisconsin is slightly cheaper statewide.',
    body: ['Winter heating and maintenance must be modeled.', 'Both states have stable long-term appreciation profiles.'],
    metricsTable: [{ label: 'Median home price', a: '$335,000', b: '$265,000' }],
    faq: [{ question: 'How much do winters cost?', answer: 'Heating and snow-related maintenance can add meaningfully to annual ownership cost.' }],
    meta: { title: 'Minnesota vs. Wisconsin: Buy or Rent', description: 'MN vs. WI housing comparison.' },
  },
  {
    slug: 'colorado-vs-utah',
    kind: 'state-vs-state',
    title: 'Colorado vs. Utah: Buy or Rent?',
    subtitle: 'Mountain West hubs with growing economies.',
    sideA: { name: 'Colorado', highlights: ['Denver/Boulder corridor', 'Strong appreciation'] },
    sideB: { name: 'Utah', highlights: ['Salt Lake City growth', 'Younger demographics'] },
    bluf: 'Both states favor buying within 5-6 years with stable incomes; Utah is slightly cheaper.',
    body: ['Wildfire insurance has become a factor in some Colorado markets.', 'Utah has experienced fast population and housing growth.'],
    metricsTable: [{ label: 'Median home price', a: '$545,000', b: '$520,000' }],
    faq: [{ question: 'Is wildfire risk priced in?', answer: 'Increasingly yes, via higher insurance premiums and lender requirements.' }],
    meta: { title: 'Colorado vs. Utah: Buy or Rent', description: 'Colorado vs. Utah housing comparison.' },
  },
];

export const getComparison = (slug: string) =>
  comparisons.find((c) => c.slug === slug);
