import { ScenarioData } from './pageTypes';

const mk = (
  slug: string,
  title: string,
  persona: string,
  bluf: string,
  sectionsArr: [string, string][],
  factors: string[],
  verdict: string,
  faqArr: [string, string][],
  desc: string
): ScenarioData => ({
  slug,
  title,
  persona,
  bluf,
  sections: sectionsArr.map(([heading, body]) => ({ heading, body })),
  factors,
  verdict,
  faq: faqArr.map(([question, answer]) => ({ question, answer })),
  meta: {
    title: `${title} | Buy vs. Rent Scenario`,
    description: desc,
  },
});

export const scenarios: ScenarioData[] = [
  mk(
    'short-stay-3-years',
    'Short stay under 3 years: buy or rent?',
    'Someone planning to move within 3 years (job rotation, grad school, visa-bound).',
    'For stays under 3 years, renting almost always wins financially because transaction costs (closing, sale fees) consume equity gains.',
    [
      ['Why break-even rarely arrives in 3 years', 'Closing costs (2-5%), selling costs (5-7% with agent), and the early-amortization tilt toward interest mean you build little equity.'],
      ['When buying short-term can still work', 'Rapidly appreciating markets, no-agent sale, or a clear buyer lined up. These are edge cases, not defaults.'],
      ['The renter advantage', 'Flexibility to relocate for a better job, avoid maintenance surprises, and keep more liquid savings.'],
    ],
    ['Closing costs', 'Selling costs', 'Early amortization', 'Opportunity cost of down payment', 'Local appreciation rate'],
    'Rent, and invest the saved capital. Revisit the buy decision when your horizon reaches 5+ years.',
    [
      ['Is there ever a 3-year break-even?', 'In unusually hot markets, yes, but it is speculative. Plan conservatively.'],
      ['What about cash buyers?', 'Cash buyers avoid mortgage interest but still face transaction costs. The math is closer but often still favors renting short-term.'],
    ],
    'Short-term stay under 3 years: should you buy or rent?'
  ),
  mk(
    'family-of-4-buy-or-rent',
    'Family of 4: buy or rent?',
    'Dual-income family with two children considering school districts and stability.',
    'Families with 5+ year horizons often benefit from buying when school stability and space needs outweigh flexibility.',
    [
      ['Why stability matters', 'Moving costs for families compound. Buying in a good school district locks in access.'],
      ['The space premium', 'Single-family rentals often cost more per sqft than owning.'],
      ['Risks to manage', 'Major repairs, property tax increases, school district changes.'],
    ],
    ['School district', 'Commute changes', 'Maintenance budget', 'Child-related moves over 10 years'],
    'Buy if horizon is 5+ years, you have 3-6 months emergency fund after down payment, and the school district is stable.',
    [
      ['How much emergency fund should families keep?', 'Generally 3-6 months of expenses after closing, separate from the down payment.'],
      ['Does renting a house ever beat buying for families?', 'In very expensive markets, yes — especially with volatile job paths.'],
    ],
    'Family of four: buy versus rent decision analysis.'
  ),
  mk(
    'remote-worker-relocation',
    'Remote worker relocating: buy or rent?',
    'Remote employee relocating to a new metro without office anchoring.',
    'Rent first for 6-12 months, then decide. Neighborhood fit matters more than entry-price timing for most remote workers.',
    [
      ['Why rent first', 'You cannot predict which neighborhood fits before living in a metro.'],
      ['What to evaluate in your rental year', 'Commute patterns (even remote workers commute to coffee/gyms), HOA rules, noise profiles.'],
      ['When to buy', 'Once you have confidence in a specific ZIP or neighborhood and a 5+ year plan.'],
    ],
    ['Internet reliability', 'Home office space', 'Utility costs', 'Local HOA restrictions'],
    'Rent for at least 6-12 months before buying in a new metro.',
    [
      ['Is buying sight-unseen risky?', 'Yes — relocation regret is common when bought too fast.'],
      ['What about employer relocation packages?', 'Use them to cover the rental year and defer the purchase decision.'],
    ],
    'Remote workers relocating: buy or rent strategy.'
  ),
  mk(
    'first-time-buyer-low-down-payment',
    'First-time buyer with low down payment',
    'First-time buyer with 3-5% down looking at FHA/conventional-97 options.',
    'Low down payments make ownership accessible but increase PMI cost, interest burden, and sensitivity to price drops.',
    [
      ['Entry programs', 'FHA and conventional-97 products allow 3-5% down with PMI.'],
      ['PMI economics', 'Typically 0.3-1.5% annually until 20% equity is reached.'],
      ['Risk factors', 'If prices drop 5-10%, you can be underwater with low down payments.'],
    ],
    ['PMI cost', 'Interest rate', 'Local price volatility', 'Job stability', 'Emergency fund post-closing'],
    'Buy with low down payment if you plan to stay 5+ years and have an emergency fund after closing.',
    [
      ['Can I drop PMI later?', 'Usually yes, at 20% equity on conventional; FHA requires refinancing in most cases.'],
      ['Should I wait to save 20%?', 'Sometimes — but rent and price appreciation during the wait can offset the savings.'],
    ],
    'First-time buyer with low down payment: buy vs. rent.'
  ),
  mk(
    'high-rent-city-vs-buying-suburb',
    'High-rent city vs. buying in the suburbs',
    'Someone renting expensively downtown, considering a suburban home purchase.',
    'This tradeoff trades commute time and amenities for equity building and space.',
    [
      ['The commute cost', 'Model fuel, transit, and time.'],
      ['The lifestyle change', 'Restaurants, nightlife, and network proximity matter.'],
      ['The math', 'Add commute cost to the suburban ownership total, then compare.'],
    ],
    ['Commute hours per week', 'Transportation cost', 'Downtown rent growth rate'],
    'Suburban buying usually wins over 6+ years if the commute cost is tolerable.',
    [
      ['Does remote work flip this?', 'Yes — if you never commute, suburban economics are even stronger.'],
      ['Any downsides to suburbs?', 'Fewer third places, more car dependence, different social structure.'],
    ],
    'High-rent city versus suburban buying analysis.'
  ),
  mk(
    'unsure-how-long-youll-stay',
    'Unsure how long you will stay: buy or rent?',
    'Someone without a clear timeline — job or life situation in flux.',
    'When uncertain, rent. Flexibility is the valuable asset; buying locks in illiquidity.',
    [
      ['Optionality has value', 'Renting preserves the option to move for a better job without transaction drag.'],
      ['Signal, don\'t guess', 'Look for signals: engagement, job stability, school needs.'],
      ['Set a review date', 'Decide to revisit the decision every 12 months.'],
    ],
    ['Job tenure expectation', 'Relationship stability', 'Family planning uncertainty'],
    'Default to renting when uncertain; plan a 12-month review.',
    [
      ['Am I throwing money away by renting?', 'No — you are paying for flexibility and zero maintenance obligation.'],
    ],
    'Unsure how long you will stay: buy or rent guidance.'
  ),
  mk('retiree-downsizing', 'Retiree downsizing: buy or rent?', 'Retiree evaluating a smaller home or rental apartment.',
    'Downsizing decisions depend on equity release, portfolio needs, and maintenance tolerance.',
    [
      ['Equity release from selling', 'Can fund retirement needs or investments.'],
      ['Maintenance load', 'Renting eliminates it; owning keeps the control.'],
      ['Healthcare and mobility', 'Plan 10-15 years ahead.'],
    ],
    ['Cash flow needs', 'Healthcare access', 'Family proximity'],
    'If your portfolio covers expenses, renting reduces hassle. If you need home equity as a store of value, owning a smaller home can work.',
    [['Is renting a failure in retirement?', 'No — many retirees choose renting for the flexibility and reduced responsibility.']],
    'Retiree downsizing: buy or rent.'
  ),
  mk('divorce-transition', 'After divorce: buy or rent?', 'Someone in a life transition after divorce.',
    'Most advisors suggest renting for 12-24 months after divorce to stabilize finances and avoid regret purchases.',
    [
      ['Emotional decisions', 'Post-separation purchases often underperform.'],
      ['Financial picture', 'Credit, income, and legal settlements should be clear first.'],
    ],
    ['Custody arrangements', 'School needs', 'Financial stability'],
    'Rent for 12-24 months, then decide.',
    [['Can I buy before the divorce is final?', 'Legally complex and often inadvisable without counsel.']],
    'Post-divorce buy vs. rent guidance.'
  ),
  mk('new-job-relocation', 'Starting a new job in a new city', 'Professional relocating for a new role.',
    'Rent for the first year unless you have deep local knowledge and high job confidence.',
    [['Probation periods', 'Most roles have 90-180 day probation — a risky time to sign a mortgage.']],
    ['Job probation', 'Market familiarity', 'Employer relocation benefits'],
    'Rent for 12 months, buy when conviction is high.',
    [['What if my employer covers buy costs?', 'Still rent first — most regret buying too quickly.']],
    'New job relocation: buy or rent.'
  ),
  mk('student-loan-heavy', 'Heavy student loan debt: buy or rent?', 'Early-career professional with significant student debt.',
    'Prioritize emergency fund and debt management before buying. Do not stretch to buy on thin margins.',
    [['DTI impact', 'Student debt raises DTI and affects mortgage approvals.']],
    ['Interest rates on loans', 'Income trajectory', 'Emergency fund'],
    'Rent until debt and savings are stable.',
    [['Should I pay off loans before buying?', 'Not necessarily — balance both if rates allow.']],
    'Student loan heavy: buy or rent.'
  ),
  mk('young-couple-starter-home', 'Young couple buying a starter home', 'Newly married or partnered couple.',
    'Starter homes can work if you plan to stay 5+ years; short-term starter purchases underperform.',
    [['Stretching to buy', 'Common regret: buying too much house too early.']],
    ['Joint income stability', 'Family planning', 'Career flexibility'],
    'Buy only if horizon exceeds 5 years.',
    [['Is a starter home still worth it?', 'Yes, if the tenure matches the transaction cost math.']],
    'Young couple starter home decision.'
  ),
  mk('single-professional-condo', 'Single professional considering a condo', 'Single professional in a major metro.',
    'Condos work when HOA, transfer costs, and exit liquidity are acceptable. Evaluate HOA health carefully.',
    [['HOA reserve funds', 'Under-reserved HOAs create special-assessment risk.']],
    ['HOA reserves', 'Special assessments', 'Condo rules'],
    'Buy if horizon is 6+ years and the HOA is healthy.',
    [['Can condos beat apartments?', 'Yes, over 6+ year horizons in most metros.']],
    'Single professional condo decision.'
  ),
  mk('growing-family-second-home', 'Growing family upgrading homes', 'Family considering selling and buying a larger home.',
    'Upgrade math depends on rate differential, selling costs, and tenure in the new home.',
    [['Rate lock-in effect', 'Low-rate mortgages lock in favorable monthly payments worth modeling.']],
    ['Rate differential', 'Selling/buying costs', 'Equity available'],
    'Model both options in the calculator before upgrading.',
    [['Is rate lock-in enough to stay?', 'Sometimes yes — the implicit subsidy can exceed the upgrade benefit.']],
    'Growing family upgrading homes.'
  ),
  mk('empty-nester-move', 'Empty nester move', 'Parents whose children have left home.',
    'Downsizing frees equity; renting offers flexibility; staying reduces friction.',
    [['Memory cost', 'Emotional attachment often inflates the value of staying.']],
    ['Retirement plans', 'Location preferences', 'Healthcare proximity'],
    'Move only when the financial case and the lifestyle case align.',
    [['Should I rent during transition?', 'Often yes — test new locations before buying.']],
    'Empty nester move decision.'
  ),
  mk('investment-vs-primary-home', 'Investment property vs. primary home', 'Someone considering buying a rental instead of a home.',
    'Investment properties require different analysis — cap rates, vacancy, management cost, tax treatment.',
    [['Why the analysis differs', 'Cash flow, not personal use, is the metric.']],
    ['Cap rate', 'Vacancy allowance', 'Management cost'],
    'Only invest in rentals with clear cash-flow positive math.',
    [['Can I house-hack?', 'Yes — owner-occupied duplexes are a common entry strategy.']],
    'Investment property vs. primary home.'
  ),
  mk('coastal-vs-inland', 'Coastal vs. inland housing decision', 'Buyer weighing coastal premium and insurance risk.',
    'Coastal carries premium pricing and rising insurance; inland offers stability and lower cost.',
    [['Insurance trend', 'Coastal insurance premiums have risen meaningfully in recent cycles.']],
    ['Hurricane / flood risk', 'Insurance cost', 'Resale liquidity'],
    'Buy coastal only if you accept insurance volatility.',
    [['Can insurance make coastal unaffordable?', 'Yes — in some markets it already has.']],
    'Coastal vs. inland housing decision.'
  ),
  mk('hoa-heavy-neighborhood', 'Buying in an HOA-heavy neighborhood', 'Buyer considering a home with a mandatory HOA.',
    'HOA fees can match or exceed property taxes. Evaluate rules, reserves, and litigation history.',
    [['HOA financial health', 'Ask for reserve study documents.']],
    ['Monthly fee', 'Reserve study', 'Covenants'],
    'Budget HOA into ownership cost; read the CC&Rs fully.',
    [['Can HOA fees rise?', 'Yes — special assessments and annual dues can increase substantially.']],
    'HOA-heavy neighborhood considerations.'
  ),
  mk('cash-buyer-strategy', 'Cash buyer strategy', 'Buyer with enough liquidity to pay in cash.',
    'Cash purchases avoid interest but incur opportunity cost. Model the invested alternative.',
    [['Opportunity cost', 'Cash tied up in a home does not earn market returns.']],
    ['Expected portfolio return', 'Mortgage rate alternative', 'Liquidity needs'],
    'Cash is usually financially comparable to a low-rate mortgage; pick based on preference and rates.',
    [['Is cash always best?', 'No — at low mortgage rates, financing and investing can beat cash purchase.']],
    'Cash buyer strategy analysis.'
  ),
  mk('house-hacking-duplex', 'House-hacking a duplex', 'Owner-occupier buying a 2-4 unit property.',
    'House-hacking can accelerate wealth building but adds landlord responsibility.',
    [['FHA options', 'Owner-occupied multi-unit financing is available with low down payments.']],
    ['Rental income', 'Tenant management', 'Maintenance scale'],
    'Works best for hands-on owners with 5+ year horizons.',
    [['Can I manage tenants while working full-time?', 'Yes — but budget 4-8 hours per month for management.']],
    'House-hacking duplex strategy.'
  ),
  mk('relocating-for-school', 'Relocating for a school district', 'Parents moving for school access.',
    'Ownership can lock in district access; renting preserves flexibility if the child switches schools.',
    [['Boundary risk', 'School district boundaries can be redrawn.']],
    ['School district stability', 'Boundary maps', 'Child ages'],
    'Buy if you expect 5+ years and the district is stable.',
    [['Are charter/magnet schools a factor?', 'Yes — they can weaken the district-boundary argument for buying.']],
    'Relocating for school district analysis.'
  ),
  mk('two-income-household-optimizer', 'Two-income household optimization', 'Couple with two stable incomes.',
    'Dual incomes expand the buy option set; use the extra income for savings and flexibility, not maxing DTI.',
    [['Income risk', 'Model the loss of one income — can you still cover the payment?']],
    ['Income stability', 'Emergency fund'],
    'Use dual incomes to buy less house than you could qualify for.',
    [['Should we buy at the max approval?', 'Rarely — it creates fragility.']],
    'Two-income household optimization.'
  ),
  mk('one-income-household', 'One-income household buying', 'Single-earner family considering a home.',
    'Single-income buyers need larger emergency funds and conservative DTI.',
    [['Protection strategies', 'Disability insurance, larger emergency fund.']],
    ['DTI ratio', 'Disability coverage'],
    'Target 25% of net income on all housing costs.',
    [['Is buying risky on one income?', 'More than dual — but doable with conservative planning.']],
    'One-income household buying.'
  ),
  mk('military-pcs-move', 'Military PCS move: buy or rent?', 'Active-duty member with PCS cycle.',
    'Short tenure + VA loan can work; many service members prefer renting due to 2-3 year cycles.',
    [['VA loan advantages', 'No PMI, favorable rates.']],
    ['PCS cycle length', 'BAH coverage', 'Resale timing'],
    'Rent unless tenure exceeds 4 years.',
    [['Can I rent out after PCS?', 'Yes, but consider management cost and rent vs. mortgage math.']],
    'Military PCS move decision.'
  ),
  mk('high-cost-of-living-city', 'Living in a high-cost-of-living city', 'Professional in NYC, SF, LA, Boston.',
    'HCOL cities typically favor renting for shorter stays; buying requires 8+ years and stable earnings.',
    [['Transaction cost load', 'Closing and selling costs scale with price.']],
    ['Income growth', 'Tenure', 'Transaction costs'],
    'Rent unless you have long tenure and strong equity plans.',
    [['Does rent control help?', 'Yes — it can extend the rent-wins horizon.']],
    'High-cost-of-living city strategy.'
  ),
  mk('low-cost-of-living-city', 'Living in a low-cost-of-living city', 'Resident of affordable Midwest or Southern metro.',
    'LCOL cities often favor buying within 3-4 years due to low prices and modest taxes.',
    [['Break-even math', 'Low entry prices mean less transaction drag in percentage terms.']],
    ['Local economy', 'Appreciation expectations'],
    'Buy if horizon exceeds 3-4 years.',
    [['Do LCOL cities appreciate?', 'Slower than coastal metros but more stable.']],
    'Low-cost-of-living city strategy.'
  ),
  mk('bridge-to-buy', 'Bridge from renting to buying', 'Renter planning the transition to homeownership.',
    'Set a 12-24 month runway: improve credit, save for down payment and reserves, pre-approval.',
    [['Credit score lift', 'Small improvements can lower the rate meaningfully.']],
    ['Credit score', 'Down payment target', 'Reserve fund'],
    'Plan the runway; do not rush the closing.',
    [['How much do I need saved?', 'Down payment + closing + 3-6 months reserves.']],
    'Bridge from renting to buying.'
  ),
  mk('inheritance-sudden-capital', 'Sudden capital from an inheritance', 'Someone receiving a lump sum windfall.',
    'Do not rush to buy. Park the funds, plan, and decide in 6-12 months.',
    [['Behavioral risk', 'Windfall purchases often underperform.']],
    ['Tax treatment', 'Estate advice', 'Personal timeline'],
    'Wait 6-12 months, take advice, then decide.',
    [['Where to park funds?', 'Short-term Treasuries or high-yield savings.']],
    'Sudden capital from inheritance.'
  ),
  mk('variable-income-freelancer', 'Variable-income freelancer', 'Self-employed person with lumpy income.',
    'Freelancers face stricter underwriting. Expect 2 years of tax returns and larger reserves.',
    [['Underwriting', 'Self-employed borrowers are scrutinized more.']],
    ['Income history', 'Reserve fund', 'DTI'],
    'Build 12+ months of reserves and document income carefully.',
    [['Can I use bank statement loans?', 'Yes — at higher rates typically.']],
    'Variable-income freelancer guidance.'
  ),
  mk('foreclosure-short-sale-recovery', 'Recovering from past foreclosure/short sale', 'Applicant with past distressed credit event.',
    'Wait periods apply for FHA, VA, and conventional. Rebuild credit deliberately.',
    [['Wait times', 'Typically 2-7 years depending on loan type.']],
    ['Credit recovery', 'Reserves', 'Income stability'],
    'Plan the return to ownership methodically.',
    [['Can I buy with a 620 score?', 'FHA yes; better rates require higher scores.']],
    'Foreclosure recovery buy or rent.'
  ),
  mk('climate-risk-move', 'Climate-risk-driven move', 'Household considering relocating to avoid climate exposure.',
    'Climate risk is increasingly priced into insurance and resale value. Factor it into long-term analysis.',
    [['Insurance trends', 'Climate-exposed markets are seeing premium increases.']],
    ['Hurricane, flood, wildfire risk', 'Resale liquidity'],
    'Model insurance and resale carefully.',
    [['Is this speculative?', 'Less so each year — insurers are pricing it.']],
    'Climate-risk-driven move strategy.'
  ),
];

export const getScenario = (slug: string) =>
  scenarios.find((s) => s.slug === slug);
